import Link from "next/link";

const countries = [
  "Germany", "England", "USA", "France", "Netherlands", "Belgium", "Sweden", "Switzerland", "Denmark", "Iceland", "Russia", "Ukraine", "Australia", "Romania", "Poland", "Albania", "Macedonia", "Turkey", "Nicaragua", "Dominican Republic", "Chile", "Ghana", "Sudan", "Morocco", "Ivory Coast", "Nigeria", "Malaysia", "Tunisia", "Algeria", "Azerbaijan", "Uzbekistan", "Turkmenistan", "Armenia", "Pakistan", "India", "Kuwait", "Saudi Arabia", "Qatar", "Libya", "Lebanon", "Syria", "Iraq", "Afghanistan"
];

export default function CustomersPage() {
  return <main className="min-h-screen bg-[#f3f1ec] text-[#111820]">
    <nav className="flex h-20 items-center justify-between border-b border-black/10 px-6 md:px-10"><Link href="/" className="text-xl font-black tracking-[-.04em]">KHANDABI<span className="text-[#e76f32]">.</span></Link><div className="flex items-center gap-6 text-[10px] font-bold uppercase tracking-[.18em]"><Link href="/machinery">Machinery</Link><Link href="/exhibitions">Exhibitions</Link><Link href="/">Home</Link></div></nav>
    <header className="grid border-b border-black/10 md:grid-cols-[1.15fr_.85fr]"><div className="px-6 py-20 md:px-10 md:py-28"><p className="text-[10px] font-bold uppercase tracking-[.25em] text-[#e76f32]">Customers / Global footprint</p><h1 className="mt-6 text-[clamp(4rem,9vw,9rem)] font-medium leading-[.78] tracking-[-.075em]">BUILT<br />AROUND<br /><span className="text-[#e76f32]">THE WORLD.</span></h1></div><div className="flex items-end bg-[#111820] px-6 py-16 text-white md:px-10 md:py-20"><div><p className="text-6xl font-medium tracking-[-.06em]">400+</p><p className="mt-3 text-sm text-white/50">Factories in Iran referenced by Khandabi's customer record.</p><div className="mt-8 h-px w-12 bg-[#e76f32]" /><p className="mt-6 text-6xl font-medium tracking-[-.06em]">43</p><p className="mt-3 text-sm text-white/50">Foreign countries listed in the company's published customer page.</p></div></div></header>
    <section className="px-6 py-20 md:px-10 md:py-28"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.25em] text-[#e76f32]">International presence</p><h2 className="mt-5 text-[clamp(3rem,7vw,7rem)] font-medium leading-[.82] tracking-[-.07em]">43 MARKETS<br /><span className="text-black/20">LISTED.</span></h2></div><p className="max-w-md text-sm leading-7 text-black/50">These are the countries named on Khandabi's published customer page. We keep the wording as a historical company claim rather than turning it into an unverified current sales map.</p></div><div className="mt-14 grid border-t border-black/10 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{countries.map((country, i) => <div key={country} className="flex items-center justify-between border-b border-black/10 px-3 py-4 text-sm"><span>{country}</span><span className="text-[9px] text-[#e76f32]">{String(i + 1).padStart(2, "0")}</span></div>)}</div></section>
    <section className="grid border-t border-black/10 md:grid-cols-2"><div className="bg-[#e7e3da] px-6 py-20 md:px-10 md:py-28"><p className="text-[10px] font-bold uppercase tracking-[.25em] text-[#e76f32]">Our base</p><h2 className="mt-5 text-5xl font-medium tracking-[-.06em]">IRAN FACTORY</h2><p className="mt-6 max-w-md text-sm leading-7 text-black/55">No.69, Dordaneh Alley, Emamzadeh Blvd., Shahre Qods, Karaj Old Road (20km), Tehran, Iran.</p></div><div className="bg-[#d8d4cc] px-6 py-20 md:px-10 md:py-28"><p className="text-[10px] font-bold uppercase tracking-[.25em] text-[#e76f32]">Regional presence</p><h2 className="mt-5 text-5xl font-medium tracking-[-.06em]">TURKEY</h2><p className="mt-6 max-w-md text-sm leading-7 text-black/55">No.339, Block C-6, Eskoop Industrial Area, Ikitelli – Basaksehir, Istanbul, Turkey.</p></div></section>
    <section className="bg-[#e76f32] px-6 py-20 md:px-10 md:py-28"><div className="flex flex-col justify-between gap-10 md:flex-row md:items-end"><h2 className="text-[clamp(3.5rem,8vw,8rem)] font-medium leading-[.8] tracking-[-.07em]">YOUR MARKET.<br />OUR ENGINEERING.</h2><Link href="/contact" className="w-fit border border-black/35 px-6 py-4 text-[9px] font-bold uppercase tracking-[.18em] transition hover:bg-black hover:text-white">Start a project →</Link></div></section>
  </main>;
}
